// Next.js API route support: https://nextjs.org/docs/api-routes/introduction

export default function handler(req, res) {
  res.status(200).json([
    {
      name: "Glock-18",
      type: "secondary",
      side: "BOTH",
      price: "200",
      reward: "300",
    },
    {
      name: "USP-S",
      type: "secondary",
      side: "CT",
      price: "200",
      reward: "300",
    },
    {
      name: "P2000",
      type: "secondary",
      side: "CT",
      price: "200",
      reward: "300",
    },
    {
      name: "Berettas Duplas",
      type: "secondary",
      side: "BOTH",
      price: "300",
      reward: "300",
    },
    {
      name: "P250",
      type: "secondary",
      side: "BOTH",
      price: "300",
      reward: "300",
    },
    {
      name: "Tec-9",
      type: "secondary",
      side: "TR",
      price: "500",
      reward: "300",
    },
    {
      name: "CZ75-Auto",
      type: "secondary",
      side: "BOTH",
      price: "500",
      reward: "300",
    },
    {
      name: "Five-SeveN",
      type: "secondary",
      side: "CT",
      price: "500",
      reward: "300",
    },
    {
      name: "Desert Eagle",
      type: "secondary",
      side: "BOTH",
      price: "700",
      reward: "300",
    },
    {
      name: "R8 Revolver",
      type: "secondary",
      side: "BOTH",
      price: "600",
      reward: "300",
    },
    {
      name: "AK-47",
      type: "primary",
      side: "TR",
      price: "2700",
      reward: "300",
    },
    {
      name: "M4A4",
      type: "primary",
      side: "CT",
      price: "3100",
      reward: "300",
    },
    {
      name: "M4A1-S",
      type: "primary",
      side: "CT",
      price: "2900",
      reward: "300",
    },
    {
      name: "Galil AR",
      type: "primary",
      side: "TR",
      price: "1800",
      reward: "300",
    },
    {
      name: "SSG 08",
      type: "primary",
      side: "BOTH",
      price: "1700",
      reward: "300",
    },
    {
      name: "SG 553",
      type: "primary",
      side: "TR",
      price: "3000",
      reward: "300",
    },
    {
      name: "AUG",
      type: "primary",
      side: "CT",
      price: "3300",
      reward: "300",
    },
    {
      name: "G3SG1",
      type: "primary",
      side: "BOTH",
      price: "5000",
      reward: "300",
    },
    {
      name: "M249",
      type: "primary",
      side: "BOTH",
      price: "5200",
      reward: "300",
    },
    {
      name: "Negev",
      type: "primary",
      side: "BOTH",
      price: "1700",
      reward: "300",
    },
    {
      name: "AWP",
      type: "primary",
      side: "BOTH",
      price: "4750",
      reward: "100",
    },
    {
      name: "Nova",
      type: "primary",
      side: "BOTH",
      price: "1050",
      reward: "900",
    },
    {
      name: "XM1014",
      type: "primary",
      side: "BOTH",
      price: "2000",
      reward: "900",
    },
    {
      name: "Sawed-Off/Cano Curto",
      type: "primary",
      side: "BOTH",
      price: "1100",
      reward: "900",
    },
    {
      name: "MAG-7",
      type: "primary",
      side: "CT",
      price: "1300",
      reward: "900",
    },
    {
      name: "MAC-10",
      type: "primary",
      side: "TR",
      price: "1050",
      reward: "600",
    },
    {
      name: "MP9",
      type: "primary",
      side: "CT",
      price: "1250",
      reward: "600",
    },
    {
      name: "MP5-SD",
      type: "primary",
      side: "BOTH",
      price: "1500",
      reward: "600",
    },
    {
      name: "MP7",
      type: "primary",
      side: "BOTH",
      price: "1500",
      reward: "600",
    },
    {
      name: "UMP-45",
      type: "primary",
      side: "BOTH",
      price: "1200",
      reward: "600",
    },
    {
      name: "P90",
      type: "primary",
      side: "BOTH",
      price: "2350",
      reward: "600",
    },
    {
      name: "PP-Bizon",
      type: "primary",
      side: "BOTH",
      price: "1050",
      reward: "600",
    },
  ]);
}
